import { asset } from "@/lib/korta-data";

export type Project = {
  slug: string;
  name: string;
  location: string;
  externalHref: string;
  description: string[];
  cardImage: string;
  heroImage: string;
  gallery: string[];
  logo?: string;
};

export const projects: Project[] = [
  {
    slug: "baoli",
    name: "BAOLI DUBAI",
    location: "DUBAI, UAE",
    externalHref: "https://baoli-restaurant.com/",
    description: [
      "Baoli Dubai isn't just a restaurant-it's an immersive lifestyle destination that masterfully marries refined culinary artistry with a pulsating, cosmopolitan vibe. Set against the stunning backdrop of Dubai's most coveted beachfront locale, Baoli Dubai welcomes guests into an experience that transcends the ordinary. Here, every element has been meticulously curated to evoke both sophistication and a sense of playful indulgence.",
      "Stepping inside, guests are immediately enveloped in a stylish, contemporary interior that effortlessly balances luxury with casual ease. The design features a modern aesthetic accented by warm lighting, plush seating, and artistic details that speak to the creative spirit of the venue. Large glass panels and open spaces create an airy, inviting atmosphere, while bespoke furnishings and eclectic decor elements add an unmistakable touch of urban chic.",
      "Beyond the interior, Baoli Dubai truly comes alive on its vibrant outdoor terrace. This dynamic space is not only a feast for the senses but also a social hub where the energy of Dubai's nightlife meets relaxed poolside charm. The terrace is designed for both intimate gatherings and lively celebrations, complete with comfortable seating, ambient lighting, and panoramic views that set the stage for memorable evenings.",
      "One of the standout features of the venue is the integration of luxury and leisure in its pool and lounge area. Here, the Marbella outdoor showers are more than just functional amenities-they are a retreat unto themselves. Crafted with an eye for both style and wellness, these spa-like showers offer a refreshing escape, allowing guests to unwind and rejuvenate amidst the rhythmic hum of the poolside environment.",
    ],
    cardImage: asset("2025/01/baoli234-min-scaled.jpg"),
    heroImage: asset("2025/01/baoli231-min-scaled.jpg"),
    gallery: [
      asset("2025/01/baoli231-min-scaled.jpg"),
      asset("2025/02/Restaurant-Bar-165-2024-12-23-scaled.webp"),
      asset("2025/02/baoli-dubai-p-21-89879.jpg"),
      asset("2025/01/baoli234-min-scaled.jpg"),
      asset("2025/01/baoli233-min-scaled.jpg"),
      asset("2025/01/IMG-20250107-WA0034-min.jpg"),
      asset("2025/01/IMG-20250107-WA0035-min.jpg"),
    ],
    logo: asset("2025/01/logo-baoli-dubai.svg"),
  },
  {
    slug: "cap-juluca",
    name: "BELMOND CAP JULUCA",
    location: "Maundays Bay, Anguilla",
    externalHref: "https://www.belmond.com/hotels/north-america/caribbean/anguilla/belmond-cap-juluca/",
    description: [
      "Belmond Cap Juluca is more than just a luxury resort-it is a refined haven nestled on the pristine shores of Anguilla, where the breathtaking beauty of the Caribbean meets unparalleled elegance and comfort. Set against a backdrop of expansive white-sand beaches and the sparkling turquoise of the crystal-clear waters, the resort creates an idyllic escape that perfectly balances relaxation with sophisticated indulgence.",
      "Every detail at Cap Juluca has been thoughtfully curated to evoke a sense of understated luxury. The elegantly designed villas and suites, adorned with timeless decor and modern amenities, offer guests a private sanctuary that combines open, airy spaces with intimate touches of local craftsmanship. Floor-to-ceiling windows and private terraces frame picturesque views of the sea and lush, tropical gardens, ensuring that every moment spent here is steeped in natural beauty and tranquility.",
      "The resort's spa further elevates the guest experience by offering a serene retreat where rejuvenation is an art form. Here, traditional healing practices meet modern wellness treatments, allowing visitors to unwind with personalized therapies designed to harmonize the body and mind. From soothing massages and revitalizing facials to holistic wellness programs, every treatment is delivered with meticulous attention to detail by a team dedicated to exceptional service.",
      "A striking example of the resort's commitment to refined design is the incorporation of the Minimo shower. Crafted with clean lines and constructed from high-quality materials, the Minimo shower is not only a functional amenity but also a sculptural element that enhances the overall aesthetic of the outdoor spaces. Its minimalist design ensures that it blends effortlessly into the tropical landscape, serving as a subtle yet sophisticated nod to the modern sensibilities that define Cap Juluca.",
      "Surrounded by lush landscapes and backed by a team devoted to exceptional hospitality, Belmond Cap Juluca offers an unforgettable tropical retreat where every element-from the dazzling natural environment to the meticulously designed interiors-converges to create a sanctuary of pure luxury. Here, each moment is an invitation to relax, indulge, and experience the very best that island life has to offer.",
    ],
    cardImage: asset("2025/01/CAP-SPA-20-scaled-e1737646269147.jpg"),
    heroImage: asset("2025/01/CAP-SPA-20-scaled-e1737646269147.jpg"),
    gallery: [
      asset("2025/01/CAP-SPA-20-scaled-e1737646269147.jpg"),
      asset("2025/02/236387568.jpg"),
      asset("2025/01/CAP-ACC-EXT-21-scaled.jpg"),
      asset("2025/02/CAP-EXT-71.jpg"),
      asset("2025/02/RoomService-CapJuluca7.jpg"),
      asset("2025/01/CAP-SPA-34-scaled.jpg"),
    ],
    logo: asset("2025/01/image-2.png"),
  },
  {
    slug: "spindler",
    name: "VILLA SPINDLER",
    location: "Dubrovnik, Croatia",
    externalHref: "https://www.dubrovnikhomes.com/en/luxury-oasis.html",
    description: [
      "Heritage Villa Spindler in Dubrovnik is a charming, meticulously restored villa that offers guests an intimate and luxurious experience in one of Croatia's most iconic cities.",
      "The villa's exterior boasts traditional stone facades, arched doorways, and timeless terracotta accents that echo the city's illustrious past. Inside, elegant interiors blend classic charm with modern amenities; each room is adorned with a tasteful mix of antique furnishings and contemporary decor, creating spaces that are both sophisticated and inviting.",
      "At the heart of Heritage Villa Spindler lies a private courtyard-a serene oasis that offers a peaceful retreat from the lively streets outside. Here, lush greenery and intimate seating areas provide the perfect backdrop for a quiet moment of reflection or a relaxed evening under the stars.",
      "The villa's location is second to none. Situated in the very heart of Dubrovnik's Old Town, it places you just steps away from the city's vibrant attractions. Imagine starting your day with a leisurely stroll along ancient cobblestone streets, exploring historic fortresses, and discovering quaint cafes and renowned restaurants that have made Dubrovnik famous worldwide. Every corner of the city is steeped in history, offering endless opportunities for cultural exploration and discovery.",
      "A standout feature at Heritage Villa Spindler is the innovative Marbella outdoor shower. Designed to merge the luxury of modern amenities with the beauty of the surrounding environment, this unique shower provides a refreshing experience like no other. As you indulge in the rejuvenating cascade of water, you can gaze out toward the famous Minceta Tower in the distance-a majestic reminder of Dubrovnik's storied heritage.",
      "Every detail at Heritage Villa Spindler is dedicated to creating an unforgettable stay. The fusion of traditional Dubrovnik architecture with modern comforts offers a rare opportunity to immerse yourself in the city's rich cultural heritage while enjoying a level of luxury that caters to every need.",
    ],
    cardImage: asset("2025/01/spindler1-scaled.jpg"),
    heroImage: asset("2025/01/457191069_18238192813287149_6995055244974915748_n.jpg"),
    gallery: [
      asset("2025/01/454237754_18235098334287149_3178496855556410575_n-1.jpg"),
      asset("2025/01/457191069_18238192813287149_6995055244974915748_n.jpg"),
      asset("2025/01/457097666_18238084012287149_4669245795291386921_n.jpg"),
      asset("2025/01/457271309_18238084030287149_6943053679623946669_n.jpg"),
      asset("2025/01/457275133_18238084000287149_576803585883820357_n.jpg"),
      asset("2025/01/589050196.jpg"),
    ],
    logo: asset("2025/01/spindler_logo-transformed-1.png"),
  },
  {
    slug: "diamond-villa",
    name: "DIAMOND VILLA",
    location: "ZRNOVO Korcula, Croatia",
    externalHref: "https://www.diamondvillakorcula.com/",
    description: [
      "Diamond Villa in Korcula is an exclusive luxury retreat that promises an unforgettable escape on one of Croatia's most enchanting islands. Perched gracefully above the sparkling Adriatic Sea, this stunning villa offers panoramic views that capture the endless blue horizon and a constellation of charming islands, creating a backdrop that is both mesmerizing and serene.",
      "Upon arrival, guests are welcomed by a sleek, contemporary design that harmoniously blends modern elegance with island sophistication. Every architectural detail has been thoughtfully curated to exude a sense of refined luxury, from the minimalist clean lines and expansive glass walls that invite natural light to the tasteful, high-end finishes that adorn every corner of the villa.",
      "Inside, the spacious interiors are designed with both style and comfort in mind. The open-plan living area creates a seamless flow between the indoor and outdoor spaces, encouraging relaxation and effortless entertaining. High ceilings and large windows not only amplify the sense of space but also frame breathtaking views of the surrounding landscape and shimmering sea.",
      "Situated just a short distance from the historic charm of Korcula Town, the villa offers an ideal balance of privacy and accessibility. Here, history and modernity coexist, offering an enriching experience that complements the serene luxury of the villa.",
      "In every detail, Diamond Villa in Korcula has been designed to provide an unparalleled luxury experience. It is more than just a place to stay-it is a destination where modern comfort meets timeless elegance, where every moment is crafted to leave a lasting impression, and where the beauty of the Adriatic coast unfolds around you in all its splendor. Whether you're seeking a peaceful sanctuary to unwind or a stylish base for island exploration, Diamond Villa is the ultimate escape for the discerning traveler.",
    ],
    cardImage: asset("2025/01/diamond-villa-korcula-croatia_20-scaled-2.jpg"),
    heroImage: asset("2025/01/diamond-villa-korcula-croatia_20-scaled-2.jpg"),
    gallery: [
      asset("2025/01/diamond-villa-korcula-croatia_20-scaled-2.jpg"),
      asset("2025/01/2023-05-10.jpg"),
      asset("2025/02/PRODUCT-OUTDOOR-SHOWER-MARBELLA-MATERIAL-LIMESTONE-KANFANAR-SAMPLE-SANDBLASTED-BRUSHED-PROJECT-LOCATION-CROATIA-CLIENT-DIAMOND-VILLA-scaled.jpg"),
      asset("2025/02/PRODUCT-OUTDOOR-SHOWER-MARBELLA-MATERIAL-LIMESTONE-KANFANAR-SAMPLE-SANDBLASTED-BRUSHED-PROJECT-LOCATION-CROATIA-CLIENT-DIAMOND-VILLA--scaled.jpg"),
      asset("2025/01/diamond-villa-korcula-luxury-villas-675x855-1.jpg"),
      asset("2025/01/2020-05-17-4.jpg"),
      asset("2025/01/421375002.jpg"),
    ],
    logo: asset("2025/01/diamondvillakorcula.png"),
  },
  {
    slug: "la-maison",
    name: "LA MAISON",
    location: "SV. PETAR U SUMI Istria, Croatia",
    externalHref: "https://www.lamaisonistria.com/",
    description: [
      "La Maison, a hidden gem which offers a unique blend of high-end comfort for those who desire both luxury, and sustainability. Designed to provide a full-service experience tailored to your desires, while ensuring that every aspect of your stay is catered to with the utmost care. LaMaison connects the perfect balance of privacy, comfort and environmental responsibility where you can unwind and rejuvenate in style! With its premium materials and minimalist aesthetics, our Odino shower delivers a luxurious and refreshing experience, perfectly blending into its natural surroundings.",
      "There are places designed to offer a true refuge for the soul. These sanctuaries of tranquility provide genuine peace, harmonizing the rhythms of rural life with nature beauty. Here, time flows gently, enriched by the flavors, fragrances, and serenity of the surroundings.",
      "Deep connection to the soul of Istria, a land of vibrant colours, fragrances and traditions. Find a haven of calm where every moment is an invitation to breathe deeply and live fully.",
      "Special attention has been dedicated to every detail at LaMaison, from the designed structures to the carefully placed stones that compose the ground beneath your feet. These meticulous elements were crafted by local artisans, emphasising a commitment to authenticity and craftsmanship. Sustainability lies at the heart of LaMaison, ensuring that every aspect of your experience contributes to the well-being of both guests and the environment. This ethos is reflected in our eco-friendly practices, which encompass everything from energy-efficient operations to the use of sourced materials. By prioritising sustainability, we aim to enhance your stay with a sense of harmony and responsibility towards our natural surroundings.",
    ],
    cardImage: asset("2025/01/PRODUCT-OUTDOOR-SHOWER-MARBELLA-MATERIAL-LIMESTONE-KANFANAR-SAMPLE-POLISHED-PROJECT-LOCATION-CROATIA-CLIENT-LA-MAISON--scaled.jpg"),
    heroImage: asset("2025/01/17055609639361-1-1.jpg"),
    gallery: [
      asset("2025/01/PRODUCT-OUTDOOR-SHOWER-MARBELLA-MATERIAL-LIMESTONE-KANFANAR-SAMPLE-POLISHED-PROJECT-LOCATION-CROATIA-CLIENT-LA-MAISON--scaled.jpg"),
      asset("2025/01/Pool-Area.jpg"),
      asset("2025/01/17055609639361-1.jpg"),
      asset("2025/01/PRODUCT-OUTDOOR-SHOWER-MARBELLA-MATERIAL-LIMESTONE-KANFANAR-SAMPLE-POLISHED-PROJECT-LOCATION-CROATIA-CLIENT-LA-MAISON-1-1.jpg"),
      asset("2025/01/1688549226792.jpg"),
      asset("2025/01/PRODUCT-OUTDOOR-SHOWER-MARBELLA-MATERIAL-LIMESTONE-KANFANAR-SAMPLE-POLISHED-PROJECT-LOCATION-CROATIA-CLIENT-LA-MAISON-1-2.jpg"),
      asset("2025/01/PRODUCT-OUTDOOR-SHOWER-MARBELLA-MATERIAL-LIMESTONE-KANFANAR-SAMPLE-POLISHED-PROJECT-LOCATION-CROATIA-CLIENT-LA-MAISON-1-3.jpg"),
    ],
    logo: asset("2025/01/image-3.png"),
  },
  {
    slug: "maiora",
    name: "MAIORA LUXURY SUITES",
    location: "SALI Dugi Otok, Croatia",
    externalHref: "http://maiorasuites.hr",
    description: [
      "Maiora - Luxury Island Suites in Sali, Croatia, invites you to experience a serene retreat where modern sophistication meets the timeless charm of island living. Nestled along the sparkling Adriatic coast, Maiora offers a perfect balance of comfort and style, making it an ideal destination for those seeking a relaxing getaway in a breathtaking setting.",
      "Each suite at Maiora has been thoughtfully designed to serve as a cozy and modern sanctuary. With interiors that combine sleek contemporary design with warm, inviting touches, every room provides a peaceful retreat where you can unwind in absolute comfort. Expansive windows frame stunning views of the Adriatic, ensuring that natural light and the mesmerizing seascape are an integral part of your everyday experience. Whether you are enjoying a quiet morning with a cup of coffee or unwinding in the evening as the sun sets, the beauty of the ocean is always right before your eyes.",
      "Beyond the inviting interiors, Maiora boasts an array of outdoor spaces that celebrate the natural charm of Sali. Among these is the exquisite Marbella outdoor shower, a standout feature that offers a luxurious and refreshing way to reconnect with nature. This unique amenity not only enhances your stay but also transforms the everyday act of showering into a memorable and rejuvenating ritual.",
    ],
    cardImage: asset("2025/01/IMG_0086-scaled-1.jpg"),
    heroImage: asset("2025/01/IMG_0086-scaled-1.jpg"),
    gallery: [
      asset("2025/02/DSC06159-scaled-1.jpg"),
      asset("2025/01/IMG_9934-scaled-2.jpg"),
      asset("2025/01/IMG_9944-scaled-1.jpg"),
      asset("2025/01/IMG_0086-scaled-1.jpg"),
      asset("2025/02/Maiora-Bar-Sali-Dugi-otok15-1080x720-1.jpg"),
      asset("2025/01/IMG_0180-scaled-1.jpg"),
    ],
    logo: asset("2025/01/maiora-logo-kategorizacija-3.png"),
  },
  {
    slug: "villa-vie",
    name: "VILLA VIE",
    location: "MEDULIN Istria, Croatia",
    externalHref: "https://villavie-luxury.com/",
    description: [
      "Villa Vie is a modern luxury retreat nestled in the heart of Istria, in the charming town of Medulin. This elegantly designed villa effortlessly combines contemporary sophistication with the enchanting allure of the Mediterranean, creating an idyllic setting for those seeking both relaxation and a touch of refinement.",
      "At the centerpiece of Villa Vie's offerings is its stunning outdoor heated infinity pool. Set against a backdrop of panoramic views, the pool appears to merge seamlessly with the horizon, inviting guests to take a refreshing dip while basking in the glow of the Istrian sun. Ideally located just 100 meters from the sparkling sea, Villa Vie offers immediate access to the pristine coastline. The gentle sound of the waves and the invigorating sea breeze create an ever-present ambiance of peace and serenity, making every moment spent here feel like a rejuvenating escape.",
      "Surrounded by a lush oasis of palm trees and fragrant Mediterranean plants, Villa Vie is a visual delight. The meticulously landscaped gardens and verdant surroundings offer a striking contrast to the villa's sleek, contemporary exterior. This harmonious blend of modern architecture with nature's bounty creates a unique environment where guests can relax amidst beauty and serenity, all while enjoying the comforts of high-end living.",
      "Adding an extra layer of luxury and innovation is the Marbella outdoor shower. This exquisite feature allows you to immerse yourself in a refreshing outdoor bathing experience, perfect for rinsing off after a swim or simply relishing the crisp, fresh air. The Marbella outdoor shower is a stylish complement to the villa's design, offering both practicality and elegance in one refreshing package.",
      "Villa Vie in Medulin is more than just a place to stay-it's a destination where modern luxury meets natural beauty. With its thoughtfully curated amenities, exceptional location, and meticulous design, Villa Vie promises an unparalleled retreat for those who appreciate the finer things in life.",
    ],
    cardImage: asset("2025/01/VILLA-VIE.jpg"),
    heroImage: asset("2025/01/1636708887188.jpg"),
    gallery: [
      asset("2025/01/IMG-20210207-WA0001.jpg"),
      asset("2025/01/1636708898788-1.jpg"),
      asset("2025/01/1636708887188.jpg"),
      asset("2025/01/VILLA-VIE.jpg"),
      asset("2025/01/PRODUCT-OUTDOOR-SHOWER-MARBELLA-MATERIAL-GRANITE-SAMPLE-BRUSHED-PROJECT-LOCATION-CROATIA-CLIENT-VILLA-V.jpg"),
      asset("2025/01/IMG-20210207-WA0002-1.jpg"),
    ],
    logo: asset("2025/01/vlogo2-removebg-preview.png"),
  },
  {
    slug: "themis",
    name: "VILLA THEMIS",
    location: "SV. PETAR U SUMI Istria, Croatia",
    externalHref: "https://www.villathemis.eu/",
    description: [
      "Villa Themis is your gateway to an exceptional blend of luxury, adventure, and culinary excellence in the heart of Istria. This modern, newly built villa is a masterpiece of contemporary design, meticulously crafted to offer the perfect setting for both leisurely retreats and family vacations. The interiors are elegantly decorated in warm, inviting hues that create a soothing ambiance while highlighting the villa's refined aesthetic. Every detail, from the high-quality materials to the thoughtful layout, has been carefully selected to ensure a seamless and fully functional experience for discerning guests.",
      "Step inside Villa Themis and discover an expansive, light-filled living space designed with both style and comfort in mind. The open-plan layout is perfect for family gatherings or intimate get-togethers, allowing you to create cherished memories while enjoying state-of-the-art amenities. A fully equipped modern kitchen awaits culinary enthusiasts, where you can prepare and savor the best of Istria's regional cuisine using locally sourced ingredients. Whether you're cooking a hearty family meal or sampling gourmet dishes from nearby acclaimed restaurants, the villa serves as an ideal hub for food lovers and travelers alike.",
      "Beyond its sophisticated interiors, Villa Themis offers an array of features that elevate your stay to a new level of luxury. One standout amenity is the Marbella shower, which epitomizes modern elegance. With its sleek design and the finest materials, the Marbella shower not only provides a refreshing, spa-like experience but also seamlessly complements the villa's overall aesthetic. It's the perfect way to unwind after a day of exploring the breathtaking landscapes and cultural treasures of Istria.",
      "Situated in a region celebrated for its natural beauty and rich heritage, Villa Themis provides unparalleled access to Istria's diverse attractions. Venture out and explore charming coastal towns, historic sites, and scenic vineyards, or simply relax in the serene surroundings of the villa's private spaces. Every moment spent here is an invitation to immerse yourself in the relaxed yet vibrant lifestyle that Istria is renowned for.",
      "In essence, Villa Themis is more than just a place to stay-it is a destination that promises a harmonious balance of comfort, style, and authenticity. Whether you are seeking a luxurious rest, a culinary adventure, or a memorable family vacation, Villa Themis is the perfect setting to experience the best that Istria has to offer. Explore, indulge, and let the captivating charm of this exceptional villa transform your getaway into an unforgettable escape.",
    ],
    cardImage: asset("2025/01/17-min.jpg"),
    heroImage: asset("2025/01/15-e1716274656809.webp"),
    gallery: [
      asset("2025/01/17-min.jpg"),
      asset("2025/01/05-2-min.jpg"),
      asset("2025/01/04-1-min.jpg"),
      asset("2025/01/01-min.jpg"),
      asset("2025/01/15-e1716274656809.webp"),
    ],
    logo: asset("2025/01/Themis-logo-removebg-preview.png"),
  },
  {
    slug: "bevel",
    name: "BEVEL HOUSE",
    location: "POSTUP Peljesac, Croatia",
    externalHref: "https://bevelhouse.com/",
    description: [
      "Designed to mirror the uncompromising beauty of its surrounding, Bevel house is a stunning Croatian villa on the Peljesac peninsula that provides a feast for all senses, all year round.Bevel is born on the meeting point of sea, sky, and rich soil, in a quaint village named Postup. Postup is also the name of the iconic local wine, made from grapes handpicked on the very same hill this luxury villa is built on.",
      "With a unique, angled exterior and green rooftop, the home mimics and blends into nature - honoring the sharp, yet graceful geometry of the peninsula, and towering over a spectacular view of the Adriatic sea and nearby islands. Positioned for privacy yet providing stunning views, our Marbella model creates a unique blend of comfort and nature.In these times of living at an unprecedented pace, Bevel is a sanctuary of peace and pleasure.",
      "The fully equipped rental villa has a carefully curated interior, high ceilings, glass walls, infinity pool, spacious outdoor lounge area, home gym, a wine closet with local wines (including the house brand \"Bevel\"), and even a concierge, private chef or nanny at your request. There are no obligations, only a sea of things to experience. Surrender to the allure of total relaxation, and revel in the beauty of the truly magnificent scenery.",
    ],
    cardImage: asset("2025/01/bevel1-scaled.jpg"),
    heroImage: asset("2025/01/1686297498204.jpg"),
    gallery: [
      asset("2025/01/517123742-1.jpg"),
      asset("2025/01/1686297497156.jpg"),
      asset("2025/01/1686297497837.jpg"),
      asset("2025/01/IMG-20210904-WA0051.jpg"),
      asset("2025/01/IMG_20240501_112428-scaled.jpg"),
      asset("2025/01/1686297498204.jpg"),
    ],
  },
  {
    slug: "primosten-resort",
    name: "PRIMOSTEN RESORT",
    location: "PRIMOSTEN, Croatia",
    externalHref: "https://primosten-resort.hr/",
    description: [
      "Primosten Resort is a jewel on Croatia's stunning Dalmatian coast, where modern luxury meets the rich cultural tapestry of the Mediterranean. Set against a backdrop of rugged limestone cliffs and the sparkling Adriatic Sea, the resort offers an array of elegantly designed accommodations that combine contemporary comfort with traditional Dalmatian charm.",
      "Guests are welcomed into spacious, thoughtfully decorated rooms featuring modern amenities, private terraces, and panoramic views that capture both sunrise and sunset over the crystalline waters. The resort's culinary offerings are a celebration of local flavors, with an on-site restaurant serving expertly prepared Dalmatian specialties made from fresh, locally sourced ingredients, complemented by a stylish bar where guests can unwind with signature cocktails.",
      "Beyond its exquisite dining and accommodations, Primosten Resort boasts an inviting infinity pool, a state-of-the-art wellness center and spa offering rejuvenating treatments inspired by local traditions, and beautifully landscaped outdoor areas perfect for relaxation or intimate gatherings. Whether you are seeking a serene escape, a romantic getaway, or a venue for business events with its modern conference facilities, Primosten Resort promises an unforgettable experience that reflects the timeless beauty and warm hospitality of Croatia.",
    ],
    cardImage: asset("2025/02/469039524_18031364441585461_1336472154757585507_n.jpg"),
    heroImage: asset("2025/02/469039524_18031364441585461_1336472154757585507_n.jpg"),
    gallery: [
      asset("2025/02/468074638_18030291632585461_7676561123276878210_n-1.jpg"),
      asset("2025/02/469039524_18031364441585461_1336472154757585507_n.jpg"),
      asset("2025/02/465101044_18027630995585461_3684502124480913962_n.jpg"),
      asset("2025/02/468028361_18030211592585461_5325018729163397591_n.jpg"),
      asset("2025/02/463243253_18025497287585461_6277003887887320911_n.jpg"),
      asset("2025/02/464480302_18026816093585461_5266943688504186934_n.jpg"),
      asset("2025/02/468072881_18030211571585461_5643953070433222361_n.jpg"),
    ],
    logo: asset("2025/02/Primosten-Resort-Logo-Top-min.png"),
  },
  {
    slug: "panoramica",
    name: "VILLA PANORAMICA",
    location: "VISKOVCI Istria, Croatia",
    externalHref: "https://villapanoramica.eu/",
    description: [
      "Villa Panoramica is a completely new, low-energy building with international architectural renown. Following the idea of creating a designer property in harmony with nature, a villa has been designed for you where the mosaic of living is woven from rest, relaxation, comfort, and pleasure.",
      "Set on a gentle slope with a southwesterly orientation, the villa features four levels of interior space totaling over 500 square meters, complemented by two levels of exterior space. Attached seamlessly is a garden designed in accordance with the local tradition of olive cultivation, featuring ancient, centuries-old olive trees of the Istrian 'Bjelica' variety alongside approximately sixty young olive trees, which the owners tend to with heartfelt care and love.",
      "The mission of Ville Panoramica is to delight its guests at the highest level by creating an experience based on superior accommodation and a soothing atmosphere of privacy. Upon arriving at the estate, your days begin with the scents and sounds of nature, enhanced by an unmissable panoramic view of the sea-visible even from your bed.",
      "From dawn, accompanied by the chirping of birds, to dusk, refreshed by the maestral sea breeze, enjoy everything the villa has to offer. The outdoor area spans 300 square meters, with a swimming pool boasting panoramic views of the sea, nearby islands, the Ubas peninsula, and the Kamenjak cape, occupying almost one third of the space.",
      "Inside, the layout is divided into distinct zones: a relaxation and sleeping area on the first floor; the living room, kitchen, and outdoor kitchen on the ground floor; and an entertainment area in the basement, where you'll find a gym and a mini wellness center. Together with the pool and an outdoor professional overflow jacuzzi, these amenities ensure a complete SPA experience.",
      "Indulge in your favorite dish in the dining area within the living space or outdoors, and showcase your culinary skills in two professionally equipped kitchens. To complement the starry views of the night sky in the sleeping area, a telescope is provided-allowing you during the day to explore the sea panoramas and the coastline of Eastern and Southern Istria.",
    ],
    cardImage: asset("2025/02/IMG-32cec5234361bc6224a00291826a07ed-V-1.jpg"),
    heroImage: asset("2025/02/IMG-32cec5234361bc6224a00291826a07ed-V-1.jpg"),
    gallery: [
      asset("2025/02/PRODUCT-OUTDOOR-SHOWER-MARBELLA-MATERIAL-LIMESTONE-KANFANAR-SAMPLE-RIGATO-PROJECT-LOCATION-CROATIA-CLIENT-VILLA-PANORAMICA.jpg"),
      asset("2025/02/1689750030401.jpg"),
      asset("2025/02/IMG-477cbe36e333f9548e59c95ca9933f4c-V.jpg"),
      asset("2025/02/003.jpg"),
      asset("2025/01/PRODUCT-OUTDOOR-SHOWER-MARBELLA-MATERIAL-LIMESTONE-KANFANAR-SAMPLE-RIGATO-PROJECT-LOCATION-CROATIA-CLIENT-VILLA-PANORAMICA-11-scaled-1.jpg"),
      asset("2025/02/502361918.jpg"),
      asset("2025/02/villa-panoramica-labin-istria-1651153434811.webp"),
      asset("2025/02/1689750030311.jpg"),
    ],
  },
  {
    slug: "lioqa",
    name: "LIOQA RESORT",
    location: "PREKO Ugljan, Croatia",
    externalHref: "https://www.lioqa.com/",
    description: [
      "Lioqa Resort is a luxurious haven nestled on the enchanting Ugljan Island, located on its serene eastern coast near the charming town of Preko in Croatia's captivating Zadar archipelago. This prime location not only offers guests breathtaking views of the sparkling Adriatic Sea but also places them at the heart of a region rich with history, culture, and natural beauty.",
      "Just a short ferry ride away from the bustling city of Zadar, Preko serves as a vital link between the island's tranquil ambiance and the vibrant mainland, providing easy access to ancient ruins, local markets, and centuries-old culinary traditions.",
      "At Lioqa Resort, visitors are immersed in an environment where modern luxury seamlessly blends with traditional Dalmatian hospitality; the property boasts elegantly designed accommodations that overlook pristine beaches, secluded coves, and lush olive groves that have been a part of the island's landscape for generations.",
      "Whether lounging by the infinity pool, exploring nearby hiking trails, or enjoying fresh seafood at local konobas, guests experience a perfect balance of relaxation and adventure. Every corner of the resort reflects the timeless charm of Ugljan Island, making Lioqa Resort an ideal retreat for those looking to escape the ordinary and embrace the serene beauty and rich cultural tapestry of Croatia's coast.",
    ],
    cardImage: asset("2025/02/ugljan-pic-4.jpg"),
    heroImage: asset("2025/02/ugljan-pic-4.jpg"),
    gallery: [
      asset("2025/02/542649395.jpg"),
      asset("2025/02/LIOQA-Resort13.jpeg"),
      asset("2025/01/111-odino-xxl.jpg"),
      asset("2025/02/lioqa-resort-ugljan-LJ213.jpg.webp"),
      asset("2025/01/PRODUCT-OUTDOOR-SHOWER-ODINO-XXL-MATERIAL-LIMESTONE-KANFANAR-SAMPLE-POLISHED-PROJECT-LOCATION-CROATIA-CLIENT-LIOQA-RESORT.jpg"),
      asset("2025/02/ugljan-pic-4.jpg"),
      asset("2025/02/9N7A5894.jpg"),
    ],
    logo: asset("2025/02/LIOQA_Resort_logo_transparent-removebg-preview.png"),
  },
  {
    slug: "dajo-house",
    name: "DAJO HOUSE",
    location: "ISTRIA, CROATIA",
    externalHref: "https://www.booking.com/hotel/hr/villa-dajo.hr.html",
    description: [
      "Dajo House is a modern villa in Istria, Croatia, designed by Sandro Uzila in collaboration with Wave Studio, blending traditional and contemporary architecture with large windows, open-concept interiors, and a sophisticated black-and-wood palette. It features an open-concept layout with a combined kitchen, dining, and living area, complemented by a sleek, modern kitchen and a minimalist design with natural light and garden views. The villa also offers amenities like a sauna, private pool, and garden for relaxation, as well as modern conveniences such as free Wi-Fi and air conditioning",
    ],
    cardImage: asset("2025/11/IMG_1087.jpg"),
    heroImage: asset("2025/11/IMG_1087.jpg"),
    gallery: [
      asset("2025/11/IMG_1117.jpg"),
      asset("2025/11/IMG_1111.jpg"),
      asset("2025/11/IMG_1087.jpg"),
      asset("2025/11/IMG_1322.jpg"),
      asset("2025/11/IMG_1142.jpg"),
    ],
  },
  {
    slug: "casa-rea",
    name: "CASA REA",
    location: "ISTRIA, CROATIA",
    externalHref: "https://crovillas.com/en/villa/casa-rea",
    description: [
      "In the village of Cirkoti, near Zavrsje, sits the Istrian gem, Casa Rea, offering a captivating view of olive groves and the historic town of Motovun. Architect and designer Sandro Uzila shared how he embraced simplicity in his design and why it was so easy to integrate it into the natural environment.",
      "Probably one of the best things I've done in my life was a road trip through Istria (if you haven't yet, be sure to treat yourself to this pleasure). The soothing dance of local roads winding through the hills of Istria's interior never allows the scenery to become dull. It's clear to me why many have wished for a holiday home in this part of the world. One of the latest projects by architect and designer Sandro Uzila is Casa Rea, a house located in the small village of Cirkoti, near Zavrsje (in my opinion, one of the most charming corners of Istria), between Groznjan and Motovun. You might think of Rea as a queen, which this house indeed is at first glance (if you ask us), but it's actually a blend of the names Rene and Andrea, a beautiful tribute to the owners' sons. Although they invested in a holiday home they plan to rent out, the owners have left time for themselves to enjoy this piece of family paradise. \"I sketched the house in one night. After visiting the location, on the way to the office, I had a clear vision of how I wanted the house to look and didn't want to go to sleep until it was completely finished. The floor plan and facades were ready that same night,\" Sandro tells us, owner of one of the busiest Istrian architectural-design offices, WAVE Design Studio, whom the investors entrusted with this construction and design project. He also explains that for unique signature projects, he works under his own brand, Sandro Uzila. \"Some projects are more commercial than others, but I often have the opportunity to create such unique projects with carefully designed details and aesthetics, and the freedom to follow, of course in collaboration with the investor, ideas that I believe will turn out well.\"",
    ],
    cardImage: asset("2025/11/1.jpeg"),
    heroImage: asset("2025/11/1.jpeg"),
    gallery: [
      asset("2025/11/2.webp"),
      asset("2025/11/4.webp"),
      asset("2025/11/6.webp"),
      asset("2025/11/3.webp"),
      asset("2025/11/1.jpeg"),
      asset("2025/11/5.webp"),
    ],
  },
  {
    slug: "the-s-tower-by-sobha",
    name: "THE S TOWER by SOBHA",
    location: "DUBAI, UAE",
    externalHref: "https://sobharealty.com/apartments-for-sale-in-dubai/the-s/",
    description: [
      "The S Tower offers exclusive outdoor living spaces with views of Palm Jumeirah and the expansive horizon, in addition to quick access to Palm Jumeirah, Dubai Marina, Burj Al Arab, Mall of Emirates and Dubai Media City. The S Tower is an exclusive dream project where every facet of the tower encapsulates high-end style and sophistication. Every specification of the room is carefully crafted with premium materials and is oriented towards gorgeous views of the sea, golf course and the skyline.",
    ],
    cardImage: asset("2025/11/1.jpg"),
    heroImage: asset("2025/11/1.jpg"),
    gallery: [
      asset("2025/11/4.jpg"),
      asset("2025/11/3-scaled.jpg"),
      asset("2025/11/2-scaled.jpg"),
      asset("2025/11/1.jpg"),
      asset("2025/11/5-1-scaled.webp"),
      asset("2025/11/6-scaled.jpg"),
    ],
  },
  {
    slug: "onia-luxury",
    name: "ONIA LUXURY",
    location: "BUDVA, MONTENEGRO",
    externalHref: "https://www.booking.com/searchresults.hr.html?aid=356980&label=gog235jc-10CAsojwFCC29uaWEtbHV4dXJ5SBBYA2hliAEBmAEzuAEHyAEP2AED6AEB-AEBiAIBqAIBuAL6wKPIBsACAdICJDhiMTkyMDUxLWRmNGEtNGI2Ny1iYTY3LTgyODljNjgzODgxY9gCAeACAQ&highlighted_hotels=12684556&redirected=1&city=900039384&hlrd=user_sh&source=hotel&expand_sb=1&keep_landing=1&sid=f41e4370f0401e1f65af499e9dd48370",
    description: [
      "At Onia Luxury in Budva, Montenegro, guests can indulge in a refreshing escape with the stunning outdoor pool that serves as the centerpiece of our sports facilities. Surrounded by lush greenery and offering breathtaking views of the Adriatic Sea, the pool area is designed not only for relaxation but also for invigorating workouts. Whether you prefer a leisurely swim to start your day or an energetic lap session, the outdoor pool provides the perfect setting to stay active while soaking up the sun. The inviting atmosphere around the pool encourages socializing and leisure, making it an ideal spot for both fitness enthusiasts and those seeking a tranquil retreat. Guests can unwind on comfortable loungers, sip on refreshing beverages from the poolside bar, or join in on group water aerobics sessions.",
      "Probably one of the best things I've done in my life was a road trip through Istria (if you haven't yet, be sure to treat yourself to this pleasure). The soothing dance of local roads winding through the hills of Istria's interior never allows the scenery to become dull. It's clear to me why many have wished for a holiday home in this part of the world. One of the latest projects by architect and designer Sandro Uzila is Casa Rea, a house located in the small village of Cirkoti, near Zavrsje (in my opinion, one of the most charming corners of Istria), between Groznjan and Motovun. You might think of Rea as a queen, which this house indeed is at first glance (if you ask us), but it's actually a blend of the names Rene and Andrea, a beautiful tribute to the owners' sons. Although they invested in a holiday home they plan to rent out, the owners have left time for themselves to enjoy this piece of family paradise. \"I sketched the house in one night. After visiting the location, on the way to the office, I had a clear vision of how I wanted the house to look and didn't want to go to sleep until it was completely finished. The floor plan and facades were ready that same night,\" Sandro tells us, owner of one of the busiest Istrian architectural-design offices, WAVE Design Studio, whom the investors entrusted with this construction and design project. He also explains that for unique signature projects, he works under his own brand, Sandro Uzila. \"Some projects are more commercial than others, but I often have the opportunity to create such unique projects with carefully designed details and aesthetics, and the freedom to follow, of course in collaboration with the investor, ideas that I believe will turn out well.\" Onia Luxury's outdoor pool is more than just a place to swim; it's a vibrant hub where relaxation meets recreation, ensuring that every guest has the opportunity to maintain their fitness routine while enjoying the picturesque surroundings of Budva.",
    ],
    cardImage: asset("2025/11/1721632404216.jpg"),
    heroImage: asset("2025/11/1721632404216.jpg"),
    gallery: [
      asset("2025/11/IMG_20241022_114506-scaled.jpg"),
      asset("2025/11/1729170290461.jpg"),
      asset("2025/11/1729170291979.jpg"),
      asset("2025/11/1721632404598.jpg"),
      asset("2025/11/1721632404216.jpg"),
      asset("2025/11/1721632404445.jpg"),
      asset("2025/11/1729170290830.jpg"),
      asset("2025/11/1721632403589.jpg"),
    ],
  },
  {
    slug: "villas-parenzo",
    name: "VILLAS PARENZO",
    location: "ISTRIA, CROATIA",
    externalHref: "https://villasparenzo.hr/en",
    description: [
      "This beautiful complex of houses is located on an area of 3730 m2 in the village of Kukci, in the immediate vicinity of the city of Porec.",
      "It consists of 4 free-standing, fully furnished and equipped buildings with a view of the open sea (as the crow flies, about 2 kilometers).",
      "Carefully chosen details make the difference.",
      "Four identical houses, each built on its own plot, with modern architecture, clean lines and a very pleasant and functionally designed interior.",
      "Many design details in the villa area make the living space great for rest and relaxation. Each of the 4 villas is equipped with the same high-quality equipment and household appliances. The villas extend over two floors. On the ground floor, there is a living room, kitchen, bedroom with bathroom, additional toilet, sauna, utility room, and an outdoor toilet.",
      "On the first floor, there are three bedrooms, each with its own bathroom, and an additional room (gym or playroom).",
      "The staircase leads to the rooftop terrace with an outdoor bar, sunbathing area, and a hot tub. In the environment there is an outdoor heated pool, a sunbathing area, a covered terrace for dining, a canopy with a summer kitchen and an uncovered terrace directly next to the pool.",
      "There is a fire pit in the lower part of the yard. In the courtyard there is also a designer outdoor shower with hot water and a floor siphon.",
    ],
    cardImage: asset("2025/11/00ab60e0-aa91-4a36-8c6d-b927a2ccc770.jpeg"),
    heroImage: asset("2025/11/00ab60e0-aa91-4a36-8c6d-b927a2ccc770.jpeg"),
    gallery: [
      asset("2025/11/PRODUCT-OUTDOOR-SHOWER-MARBELLA-MATERIAL-LIMESTONE-KANFANAR-SAMPLE-SANDBLASTED-BRUSHED-PROJECT-LOCATION-CROATIA-CLIENT-PRIVATE-VIP-RESORT-ISTRIA-2323.jpg"),
      asset("2025/11/PRODUCT-OUTDOOR-SHOWER-MARBELLA-MATERIAL-LIMESTONE-KANFANAR-SAMPLE-SANDBLASTED-BRUSHED-PROJECT-LOCATION-CROATIA-CLIENT-PRIVATE-VIP-RESORT-ISTRIA.jpg"),
      asset("2025/11/PRODUCT-OUTDOOR-SHOWER-MARBELLA-MATERIAL-LIMESTONE-KANFANAR-SAMPLE-SANDBLASTED-BRUSHED-PROJECT-LOCATION-CROATIA-CLIENT-PRIVATE-VIP-RESORT-ISTRIA-32132.jpg"),
      asset("2025/11/00ab60e0-aa91-4a36-8c6d-b927a2ccc770.jpeg"),
      asset("2025/11/PRODUCT-OUTDOOR-SHOWER-MARBELLA-MATERIAL-LIMESTONE-KANFANAR-SAMPLE-SANDBLASTED-BRUSHED-PROJECT-LOCATION-CROATIA-CLIENT-PRIVATE-VIP-RESORT-ISTRIA-2.jpg"),
      asset("2025/11/4cb94575-fba3-4f18-9529-cb833e042af6.jpeg"),
      asset("2025/11/1d822647-9595-43d7-9083-3ac8b2bef87f.jpeg"),
      asset("2025/11/PRODUCT-OUTDOOR-SHOWER-MARBELLA-MATERIAL-LIMESTONE-KANFANAR-SAMPLE-SANDBLASTED-BRUSHED-PROJECT-LOCATION-CROATIA-CLIENT-PRIVATE-VIP-RESORT-ISTRIA-2-1.jpg"),
    ],
  },
  {
    slug: "villa-don-giordano",
    name: "VILLA DON GIORDANO",
    location: "ISTRIA, CROATIA",
    externalHref: "https://www.booking.com/hotel/hr/villa-don-giordano.en-gb.html?label=gog235jc-10CAsoZUISdmlsbGEtZG9uLWdpb3JkYW5vSDNYA2hliAEBmAEzuAEHyAEP2AED6AEB-AEBiAIBqAIBuAKvxaPIBsACAdICJDQxYzdkNWM2LThkMGYtNDNmZi05OWI2LTJiODU1YWU4OGQ0ZNgCAeACAQ&sid=f41e4370f0401e1f65af499e9dd48370&aid=356980&ucfs=1&arphpl=1&dest_id=9083399&dest_type=city&group_adults=2&req_adults=2&no_rooms=1&group_children=0&req_children=0&hpos=1&hapos=1&sr_order=popularity&srpvid=72b479182b370a89&srepoch=1762190005&from=searchresults",
    description: [
      "Villa Don Giordano is a contemporary luxury residence in the heart of Istria. With more than 500 m2 of carefully designed living space, the villa offers four bedrooms, six bathrooms, and spacious interiors flooded with natural light. Its design blends modern architecture with timeless elegance, complemented by a private swimming pool, generous outdoor terraces, and landscaped surroundings that frame panoramic views of the Istrian countryside. Villa Don Giordano reflects the growing demand for exclusive private retreats in Croatia - where premium architecture, refined details, and natural materials set the tone for an elevated lifestyle.",
      "Boasting air-conditioned accommodation with a private pool, garden view and a patio, Tuscan Mansion - Don Giordano Excelsior is set in Ferenci. This property offers access to a balcony, table tennis, free private parking and free WiFi. The villa has an outdoor fireplace and a hot tub. The spacious villa has 4 bedrooms, 6 bathrooms, bed linen, towels, a flat-screen TV, a dining area, a fully equipped kitchen, and a terrace with pool views. Guests can take in the ambience of the surroundings from an outdoor dining area or keep themselves warm by the fireplace on colder days. For added privacy, the accommodation features a private entrance. Barbecue facilities are at guests' disposal at the villa, and guests can also relax in the garden or go on a picnic in the picnic area. Aquapark Istralandia is 21 km from the villa, while Cathedral St. Eufemia Rovinj is 47 km away. Pula Airport is 62 km from the property, and the property offers a paid airport shuttle service.",
    ],
    cardImage: asset("2025/11/1-1.jpg"),
    heroImage: asset("2025/11/1-1.jpg"),
    gallery: [
      asset("2025/11/1-1.jpg"),
      asset("2025/11/6-1.jpg"),
      asset("2025/11/3-1.jpg"),
      asset("2025/11/714702941.jpg"),
      asset("2025/11/5.jpg"),
      asset("2025/11/714702847.jpg"),
      asset("2025/11/4-1.jpg"),
      asset("2025/11/2-1.jpg"),
    ],
  },
];

export const projectMap = new Map(projects.map((project) => [project.slug, project]));
